/*********************  P r o g r a m  -  M o d u l e ***********************/
/*!
 *        \file  z146_doc.c
 *
 *      \author  APatil
 *        $Date: 2015/10/16 18:08:00 $
 *        $Revision: 1.1 $
 *
 *      \brief   User documentation for MDIS5 Z146 driver
 *
 *     Required: -
 *
 *     \switches -
 */
 /*-------------------------------[ History ]--------------------------------
 *
 * $Log: z146_doc.c,v $
 *---------------------------------------------------------------------------
 * (c) Copyright 2016 by MEN Mikro Elektronik GmbH, Nuernberg, Germany
 ****************************************************************************/

/*! \mainpage
    The 13Z146 is a transceiver driver for the MEN_ARINC_429 RX and TX channels (16Z146).
	The MEN_ARINC_429 is a memory mapped IP-Core, which is used to receive and transmit
	data over the serial lines.
	The RX and TX channel can be used independently using RX and TX instance of the driver.
	Each instance of the RX and TX can be configured independently and has its own interrupt
	handling. According to the speed configuration of each instance a RAM size for the RX 
	channel and for the TX channel is provided, to ensure performant data transfer. 
	
    The 13Z146 provides following possibilities to configure ARINC 429 frames:
    - Transmit/Receive Speed; 12.5kHz  or 100kHz
	- Transmit/Receive parity enable/disable.
	- Transmit/Receive parity type; odd parity or even parity
	- Transmit/Receive Source/Destination Identifier enable/disable
	- Transmit/Receive Source/Destination Identifier
	- Transmit/Receive label set/reset

    \n
    \section Variants Variants
    (no variants)

    \n \section FuncDescTx Functional Description (Transmit)

    \n \subsection General General
	The transmit instance of the driver 13Z146 can be configured and used independently.
	The configuration of the transmit driver must be same as the receiver of the other end,
	in order to work the communication.
	The default configuration of the transmit driver is compatible to the receive driver.
	Any change in the transmit driver suppose to be taken into consideration for the receive
	driver in order to avoid failure of the communication.

    \n \subsection write Writing
	The M_setblock writes data from the user provided buffer to the device. The user can 
	write maximum 4096 words at a time. The 16Z146 ram fifo size for  the transmit is limited
	to 255 words. Therefore whenever the user data is more than 255 words, the interrupt routine
	is used	to transmit data.

    \n \subsection interrupts Signals
    
    A signal is generated by the driver, which was assigned using SetStat Z246_SET_SIGNAL to 
	the application, when a transmission request is completed. As the internal ram fifo size
	is limited, the user data will be stored internally and transmitted using interrupts. The user
	can uninstall signal using Z246_CLR_SIGNAL.

	\n \subsection setget Driver Configuration 
	The driver can be configured using M_setstat(), using following options:
	
	
	- Z246_TX_SPEED	:         0 = low speed: sending at 12.5 kHz, 1 = high speed: sending at 100 kHz 
							
	- Z246_PAR_EN : 0 = Bit 32 in transmit frame is used as regular data, 1 = Bit 32 transmit frame is used as parity bit
			
    - Z246_PAR_TYPE :         0 = odd parity, 1 = even parity

	- Z246_SDI_EN :  0 = Bit 9 and bit 10 in the transmit frame are regular data,
							1 = The TX_SDI shall be replace bit 9 and bit 10 in the transmit frame 

    - Z246_SDI : 0 = Replace bit 9 in ARINC 429 frame when enabled,	1 = Replace bit 10 in ARINC 429 frame when enabled

	- Z246_TX_LABEL :			0x00 ... 0xFF 
    
    \n \subsection default Default values
    M_open() and M_close() configures the transmit driver as follows: 
    
    - Transmit Speed: 100kHz
	- Transmit parity:	Enabled
	- Transmit parity type:	odd parity 
	- Transmit Source/Destination Identifier: disable
	- Transmit Source/Destination Identifier: N.A.
	- Transmit label: 0

    \n \section api_functions Supported API Functions of the Transmit Driver

    <table border="0">
    <tr>
        <td><b>API function</b></td>
        <td><b>Functionality</b></td>
        <td><b>Corresponding low level function</b></td></tr>

    <tr><td>M_open()</td><td>Open device</td><td>Z246_Init()</td></tr>

    <tr><td>M_close()     </td><td>Close device             </td>
    <td>Z246_Exit())</td></tr>
    <tr><td>M_setblock()  </td><td>Block write from device  </td>
    <td>Z246_BlockWrite()</td></tr>
    <tr><td>M_setstat()   </td><td>Set device parameter     </td>
    <td>Z246_SetStat()</td></tr>
    <tr><td>M_getstat()   </td><td>Get device parameter     </td>
    <td>Z246_GetStat()</td></tr>

    </table>
	
	    \n \section FuncDescRx Functional Description (Receive)

    \n \subsection General General
	The receive instance of the driver 13Z146 can be configured and used independently.
	The configuration of the receive driver must be same as the transmitter of the other end,
	in order to work the communication.
	The default configuration of the receive driver is compatible to the transmit driver.
	Any change in the receive driver suppose to be taken into consideration for the transmit
	driver in order to avoid failure of the communication.

    \n \subsection read Reading 
	The M_getblock reads data from the driver. The data can be received using interrupt or
	polling mode. 
	If interrupt is enabled, the driver receives the data and store it in an internal buffer.
	When data is received a signal is generated by the driver, which was assigned using 
	SetStat Z146_SET_SIGNAL to the application.	The internal buffer to store the received 
	data is limited to the 4096 words. 

	If the interrupt is disabled, the data can be received directly from the device without any
	internal buffer. For the polling mode the driver does not generate a signal. The user needs
	to read the interface, M_getblock, to check whether there is a data available.


    \n \subsection interrupts Interrupt and Signal
    
    If an interrupt is enabled the driver will send the signal which was assigned using
    SetStat Z146_SET_SIGNAL to the application when a data is received. 
	Uninstall signal using Z146_CLR_SIGNAL.

  	\n \subsection setget Driver Configuration 
	The driver can be configured using M_setstat(), using following options:
	
	- Z146_RX_SPEED	        0 = low speed: sending at 12.5 kHz, 1 = high speed: sending at 100 kHz 
							
	- Z146_PAR_EN			0 = Bit 32 in Receive frame is used as regular data, 
							1 = Bit 32 Receive frame is used as parity bit
			
    - Z146_PAR_TYPE         0 = odd parity, 
							1 = even parity

	- Z146_SDI_EN           0 = Bit 9 and bit 10 in the Receive frame are regular data,
							1 = The TX_SDI shall be replace bit 9 and bit 10 in the Receive frame 

    - Z146_SDI				0 = Replace bit 9 in ARINC 429 frame when enabled, 
							1 = Replace bit 10 in ARINC 429 frame when enabled

	- Z146_RX_SET_LABEL		0x00 ... 0xFF 
	
	- Z146_RX_RESET_LABEL	0x00 ... 0xFF 
    
    \n \subsection default Default values
    M_open() and M_close() configures the Receive driver as follows: 
    
    - Receive Speed: 100kHz
	- Receive parity:	Enabled
	- Receive parity type:	odd parity 
	- Receive Source/Destination Identifier: disable
	- Receive Source/Destination Identifier: N.A.
	- Receive label: 0
	- Receive interrupt: Enabled


    \n \section api_functions Supported API Functions of the Receive Driver
	
	<table border="0">
    <tr>
        <td><b>API function</b></td>
        <td><b>Functionality</b></td>
        <td><b>Corresponding low level function</b></td></tr>

    <tr><td>M_open()</td><td>Open device</td><td>Z146_Init()</td></tr>

    <tr><td>M_close()     </td><td>Close device             </td>
    <td>Z146_Exit())</td></tr>
	<tr><td>M_getblock()  </td><td>Block read from device   </td>
    <td>Z146_BlockRead()</td></tr>
    
    <tr><td>M_setstat()   </td><td>Set device parameter     </td>
    <td>Z146_SetStat()</td></tr>
    <tr><td>M_getstat()   </td><td>Get device parameter     </td>
    <td>Z146_GetStat()</td></tr>

    </table>

    \n \section descriptor_entries Descriptor Entries
    (no descriptor entries supported)    
    
    \n \section codes Z146 specific Getstat/Setstat codes
    see \ref getstat_setstat_codes "section about Getstat/Setstat codes"

    \n \section Documents Overview of all Documents

    \subsection z146_example  Simple example for using the driver
    z146_example.c (see example section)

*/

/** \example z146_example.c
Simple example for driver usage
*/

/** \example z146_example.c */

/*! \page dummy
  \menimages
*/

