/*********************  P r o g r a m  -  M o d u l e ***********************/
/*!
 *        \file  z146_doc.c
 *
 *      \author  APatil
 *        $Date: 2016/04/27 14:03:15 $
 *        $Revision: 1.6 $
 *
 *      \brief   User documentation for MDIS5 Z146 driver
 *
 *     Required: -
 *
 *     \switches -
 */
 /*-------------------------------[ History ]--------------------------------
 *
 * $Log: z146_doc.c,v $
 * Revision 1.6  2016/04/27 14:03:15  atlbitbucket
 * Stash autocheckin
 *
 *---------------------------------------------------------------------------
 * (c) Copyright 2016 by MEN Mikro Elektronik GmbH, Nuernberg, Germany
 ****************************************************************************/

/*! \mainpage
	The Z146 MDIS Driver Package contains:\n
	- ARINC429 RX drivers for the 16Z146_ARINC429 IP core\n
	- ARINC429 TX drivers for the 16Z246_ARINC429 IP core\n
	
	\n
	The RX and TX IP core channels can be used independently using RX and TX
	instances of the driver. Each instance of the RX and TX can be configured
	independently.
	
	\n
	The drivers provide following possibilities to configure ARINC 429 frames:
	- Transmit/Receive Speed; 12.5kHz  or 100kHz
	- Transmit/Receive parity enable/disable.
	- Transmit/Receive parity type; odd parity or even parity
	- Transmit/Receive Source/Destination Identifier enable/disable
	- Transmit/Receive Source/Destination Identifier
	- Transmit/Receive label set/reset

	\n
	\section Variants Variants
	- rx : ARINC429 RX driver
	- tx : ARINC429 TX driver

	
	\n
	\section RxFuncDesc === RX Driver Functional Description ===

	\n \subsection RxGeneral General
	The receive driver can be configured and used independently. The configuration
	of the receive driver must be same as the transmitter of the other end, in
	order to work the communication.
	The default configuration of the receive driver is compatible to the transmit
	driver.	Any change in the receive driver is supposed to be taken into consideration
	for the transmit driver in order to avoid failure of the communication.

    \n \subsection RxRead Receiving Data
	The M_getblock() reads data from the driver. The data can be received using
	interrupt or polling mode. 
	If interrupt is enabled, the driver receives the data and store it in an internal
	buffer. When data is received, a signal is generated by the driver which was
	assigned using M_setstat() #Z146_SET_SIGNAL to the application.	The internal
	buffer to store the received data is limited to the 4096 words. 

	If the interrupt is disabled, the data can be received directly from the device
	without any internal buffer. For the polling mode the driver does not generate
	a signal. To check whether there is data available, the user needs to read the 
	interface with M_getblock().


    \n \subsection RxInterrupts Interrupt and Signal
    
    If an interrupt is enabled the driver will send the signal which was assigned
    using M_setstat() #Z146_SET_SIGNAL to the application when data is received. 
	The signal can be uninstalled using #Z146_CLR_SIGNAL.

  	\n \subsection RxSetget Driver Configuration 
	The driver can be configured using M_setstat(), using following options:
	
	- #Z146_RX_SPEED\n
		0 = low speed: sending at 12.5 kHz\n
		1 = high speed: sending at 100 kHz\n 
						
	- #Z146_PAR_EN\n
		0 = Bit 32 in receive frame is used as regular data\n 
		1 = Bit 32 in receive frame is used as parity bit\n
			
    - #Z146_PAR_TYP\n
    	0 = odd parity\n 
		1 = even parity\n

	- #Z146_SDI_EN\n
		0 = Bit 9 and bit 10 in the receive frame are regular data\n
		1 = The TX_SDI shall replace bit 9 and bit 10 in the receive frame\n 

    - #Z146_SDI\n
    	0 = Replace bit 9 in ARINC 429 frame when enabled\n
		1 = Replace bit 10 in ARINC 429 frame when enabled\n

	- #Z146_RX_SET_LABEL\n
		0x00 ... 0xFF\n
			
	- #Z146_RX_RESET_LABEL\n
		0x00 ... 0xFF\n 
    
    \n \subsection RxDefault Default values
    M_open() and M_close() configures the Receive driver as follows: 
    
    - Receive Speed: 100kHz
	- Receive parity:	Enabled
	- Receive parity type:	odd parity 
	- Receive Source/Destination Identifier: disable
	- Receive Source/Destination Identifier: N.A.
	- Receive label: 0
	- Receive interrupt: Enabled


    \n \section RxApi_functions Supported API Functions of the Receive Driver
	
	<table border="0">
    <tr>
        <td><b>API function</b></td>
        <td><b>Functionality</b></td>
        <td><b>Corresponding low level function</b></td></tr>

    <tr><td>M_open()</td><td>Open device</td><td>Z146_Init()</td></tr>

    <tr><td>M_close()     </td><td>Close device             </td>
    <td>Z146_Exit())</td></tr>
	<tr><td>M_getblock()  </td><td>Block read from device   </td>
    <td>Z146_BlockRead()</td></tr>
    
    <tr><td>M_setstat()   </td><td>Set device parameter     </td>
    <td>Z146_SetStat()</td></tr>
    <tr><td>M_getstat()   </td><td>Get device parameter     </td>
    <td>Z146_GetStat()</td></tr>

    </table>

    \n \section RxDescriptor_entries Descriptor Entries
    (no descriptor entries supported)    
    
    \n \section RxCodes Driver specific Getstat/Setstat codes
    see \ref rx_getstat_setstat_codes "section about Getstat/Setstat codes"


    \n \section TxFuncDesc === TX Driver Functional Description ===

    \n \subsection TxGeneral General
	The transmit driver can be configured and used independently. The configuration
	of the transmit driver must be same as the receiver of the other end, in
	order to work the communication.
	The default configuration of the transmit driver is compatible to the receive
	driver.	Any change in the transmit driver suppose to be taken into consideration
	for the receive driver in order to avoid failure of the communication.
	
    \n \subsection TxWrite Transmitting Data
	The M_setblock() writes data from the user provided buffer to the device.
	The user can write a maximum of 4096 words at a time. The fifo size for the
	transmit is limited to 255 words. Therefore, whenever the user data is more
	than 255 words, the interrupt routine is used to transmit data.

    \n \subsection TxInterrupts Interrupt and Signal
    
    A signal is generated by the driver, which was assigned using M_setstat()
    #Z246_SET_SIGNAL to the application, when a transmission request is completed.
    As the internal ram fifo size is limited, the user data will be stored internally
    and transmitted using interrupts.
    The signal can be uninstalled using #Z246_CLR_SIGNAL.

	\n \subsection TxSetget Driver Configuration 
	The driver can be configured using M_setstat(), using following options:
	
	- #Z246_TX_SPEED\n
		0 = low speed: sending at 12.5 kHz\n
		1 = high speed: sending at 100 kHz\n 
						
	- #Z246_PAR_EN\n
		0 = Bit 32 in transmit frame is used as regular data\n 
		1 = Bit 32 in transmit frame is used as parity bit\n
			
    - #Z246_PAR_TYPE\n
    	0 = odd parity\n 
		1 = even parity\n

	- #Z246_SDI_EN\n
		0 = Bit 9 and bit 10 in the transmit frame are regular data\n
		1 = The TX_SDI shall replace bit 9 and bit 10 in the transmit frame\n 

    - #Z246_SDI\n
    	0 = Replace bit 9 in ARINC 429 frame when enabled\n
		1 = Replace bit 10 in ARINC 429 frame when enabled\n

	- #Z246_TX_LABEL\n
		0x00 ... 0xFF\n
			
    
    \n \subsection TxDefault Default values
    M_open() and M_close() configures the transmit driver as follows: 
    
    - Transmit Speed: 100kHz
	- Transmit parity:	Enabled
	- Transmit parity type:	odd parity 
	- Transmit Source/Destination Identifier: disable
	- Transmit Source/Destination Identifier: N.A.
	- Transmit label: 0

    \n \section TxApi_functions Supported API Functions of the Transmit Driver

    <table border="0">
    <tr>
        <td><b>API function</b></td>
        <td><b>Functionality</b></td>
        <td><b>Corresponding low level function</b></td></tr>

    <tr><td>M_open()</td><td>Open device</td><td>Z246_Init()</td></tr>

    <tr><td>M_close()     </td><td>Close device             </td>
    <td>Z246_Exit())</td></tr>
    <tr><td>M_setblock()  </td><td>Block write from device  </td>
    <td>Z246_BlockWrite()</td></tr>
    <tr><td>M_setstat()   </td><td>Set device parameter     </td>
    <td>Z246_SetStat()</td></tr>
    <tr><td>M_getstat()   </td><td>Get device parameter     </td>
    <td>Z246_GetStat()</td></tr>

    </table>

    \n \section TxDescriptor_entries Descriptor Entries
    (no descriptor entries supported)    
    
    \n \section TxCodes Driver specific Getstat/Setstat codes
    see \ref tx_getstat_setstat_codes "section about Getstat/Setstat codes"

    \n \section Documents Overview of all Documents

    \subsection z146_example  Simple example for using the driver
    z146_example.c (see example section)

*/

/** \example z146_example.c
Simple example for driver usage
*/

/*! \page dummy
  \menimages
*/

